name = "odin-session-worker"
main = "session_manager.js"
compatibility_date = "2025-09-25"

[[durable_objects.bindings]]
name = "SESSION_MANAGER"
class_name = "SessionManager"

[[migrations]]
tag = "v1"
new_classes = ["SessionManager"]
