name = "odinmcp"
compatibility_date = "2024-09-01"

# ✅ Pages needs this
pages_build_output_dir = "dist"

# ✅ Bind Durable Object + Worker
[[durable_objects.bindings]]
name = "SESSION_MANAGER"
class_name = "SessionManager"
script_name = "odin-session-worker"

[[migrations]]
tag = "v1"
new_classes = ["SessionManager"]
