name = "odin-session-worker"
main = "index.js"
compatibility_date = "2023-12-01"

[durable_objects]
bindings = [
  { name = "SESSION_MANAGER", class_name = "SessionManager" }
]

[[migrations]]
tag = "v1"
new_classes = ["SessionManager"]
