name = "odin-session-worker"
main = "session_manager.js"
compatibility_date = "2025-09-23"

# Define the Durable Object class
[[durable_objects.classes]]
name = "SessionManager"
class_name = "SessionManager"

# Bind the Durable Object so your Worker can use it
[durable_objects]
bindings = [
  { name = "SESSION_MANAGER", class_name = "SessionManager" }
]
