name = "odinmcp"
main = "./functions/api/session/session_manager.js"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "SESSION_MANAGER"
class_name = "SessionManager"

[[migrations]]
tag = "v1"
new_classes = ["SessionManager"]
